### ISSUE TITLE
 undefined method `tag_by_type' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by Escapingbug** [david942j/one_gadget#11]
Thanks for this project, but I got such error when I run the script on some stripped binary:
```
/home/anciety/.gem/ruby/2.4.0/gems/one_gadget-1.4.0/lib/one_gadget/fetchers/i386.rb:116:in `block in got_offset': undefined method `tag_by_type' for nil:NilClass (NoMethodError)
	from /home/anciety/.gem/ruby/2.4.0/gems/one_gadget-1.4.0/lib/one_gadget/fetchers/i386.rb:114:in `open'
	from /home/anciety/.gem/ruby/2.4.0/gems/one_gadget-1.4.0/lib/one_gadget/fetchers/i386.rb:114:in `got_offset'
	from /home/anciety/.gem/ruby/2.4.0/gems/one_gadget-1.4.0/lib/one_gadget/fetchers/i386.rb:13:in `find'
	from /home/anciety/.gem/ruby/2.4.0/gems/one_gadget-1.4.0/lib/one_gadget/fetcher.rb:45:in `from_file'
	from /home/anciety/.gem/ruby/2.4.0/gems/one_gadget-1.4.0/lib/one_gadget.rb:32:in `gadgets'
	from /home/anciety/.gem/ruby/2.4.0/gems/one_gadget-1.4.0/bin/one_gadget:48:in `<top (required)>'
	from /home/anciety/.gem/ruby/2.4.0/bin/one_gadget:22:in `load'
	from /home/anciety/.gem/ruby/2.4.0/bin/one_gadget:22:in `<main>'
```

Is it impossible to run this on stripped binary? According to this error message I assume it is caused by the stripping. Since I really don't know about Ruby, I can do little help with this..

And the binary is just defcon quals 2016 feedme challenge

**Comment by david942j** [comment]
Thanks for reporting!

This error is because the buildID is removed by `strip --remove-section .note --remove-section .comment --remove-section .note.gnu.build-id feedme`
(https://github.com/legitbs/quals-2016/blob/master/feedme/strip_all)

However, you should find one-gadgets in a glibc binary (i.e. `one_gadget /lib/x86_64-linux-gnu/libc.so.6`) but not in a normal binary.

Thanks anyway.
