### ISSUE TITLE
one_gadget requires Ruby version >= 2.4.

### ISSUE THREAD

**Issue by HolyTruth** [david942j/one_gadget#167]
here is my problem,
----------------------------------------------------
ERROR:  Error installing one_gadget:
	one_gadget requires Ruby version >= 2.4.
----------------------------------------------------
when I tried   gem install one_gadget,it appeared.  but in article it only need ruby version >= 2.1.0, by the way ,my os is Ubuntu 16.04.7 LTS and ruby version is ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu] , save me plz!

**Comment by david942j** [comment]
Well time flies.. Ruby 2.3 reached end-of-life two years ago (check https://www.ruby-lang.org/en/downloads/branches/) so using it is not a good idea. Even Ubuntu 16.04 is not maintained since this month (https://ubuntu.com/about/release-cycle)

Anyway, to deal with this you have several options

1. upgrade your Ubuntu to a newer version, then a newer Ruby would be shipped along with it
2. (preferred) use rvm or rbenv to install a new version of Ruby (2.7)
3. Use snap to install new version of Ruby, ref: https://askubuntu.com/questions/1175693/how-to-upgrade-ruby-to-version-2-4-4-on-ubuntu-16-04-for-wpscan
